### PR TITLE
add fanart and icon

### PR DESCRIPTION
**Pull request by eriksoderblom**
The base image for the fanart is from unsplash and free to use.
Since you said in #1 that it should adhere to ESPN branding I put "Powered by ESPN" on the icon, if you wish I can put it on somewhere on the fanart as well.

### CODE REVIEW

**Comment by emilsvennesson** [comment]
@eriksoderblom You're the artwork hero. This looks awesome! Thanks a lot. :smiley:

I took a look at the ESPN branding guide again, and it turns out they discontinued their open API a few months ago... So maybe it's better if we refrain from using the official ESPN logo at all?

It'd be cool if you could replace it with something else related to the service (e.g. a football or something like that).

**Comment by eriksoderblom** [comment]
@emilsvennesson  I've removed the ESPN logo now and added a background to the icon

**Comment by emilsvennesson** [comment]
@eriksoderblom Thanks! I like it, but personally I prefer the simplistic look of the first icon. You can never go wrong with a plain black background. :-) I think it would look neat if you took the first logo, moved the text up a bit and added a football for example. I'm clueless when it comes to artwork though so if you've got another idea/preference, please tell me. :-)

Also, could you please make sure it's 256x256? Even though I don't agree with it, that's the icon size the wiki specifies. :/

**Comment by eriksoderblom** [comment]
Ah, right, forgot about the size, I always work with higher resolutions and resize when save.
Will try a few things and report back with a cleaner icon :)

**Comment by eriksoderblom** [comment]
@emilsvennesson Changed the icon again, cleaner and some sports icons

**Comment by emilsvennesson** [comment]
@eriksoderblom It looks great! Thanks a lot for helping me out once again.

**Comment by emilsvennesson** [comment]
@eriksoderblom You wouldn't happen to have the original non-resized version of the icon? The official repo allows a 512x512 resolution for the icon now. :)

**Pull request merged**
